---
title: "pregunta_5"
author: "ENRIQUE"
date: "11/7/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Usando la librería syuzhet incorpore las siguientes 4 palabras en el léxico nrc:
• racista, negative, 1
• patético, anger,1
• roban, anger,1
• lacra, anger,1
Adapte la función para que el análisis de sentimiento incluya estas palabras. Verifique el funcionamiento con
la frase:
“Esa persona es racista, patético y una lacra. otros roban a las personas”
```{r}
frase<-"Esa persona es racista, patético y una lacra. otros roban a las personas"
frase<-as.character(frase)
#resultado actual
library(syuzhet)
get_nrc_sentiment(frase,language = "spanish")
## anger anticipation disgust fear joy sadness surprise trust negative positive
## 1 0 0 0 0 0 0 0 0 0 0
#resultado esperado
#ejemplo(frase,language = "spanish")
## anger anticipation disgust fear joy sadness surprise trust negative positive
## 1 2 0 0 0 0 0 0 0 1 0
2
#####################################
ww<-get_sentiment_dictionary("nrc",language = "spanish")

ww<-rbind(ww,c("spanish","racista", "negative",1 ))
ww<-rbind(ww,c("spanish","patético", "anger",1))
ww<-rbind(ww,c("spanish","roban", "anger",1))
ww<-rbind(ww,c("spanish","lacra", "anger",1))
tail(ww)
str(ww)
ww$value<-as.numeric(ww$value)

#get_nrc_sentiment
#get_nrc_values
ejemplo<-function (char_v, cl = NULL, language = "english",lexicon=T) 
{
    if (!is.character(char_v)) 
        stop("Data must be a character vector.")
    if (!is.null(cl) && !inherits(cl, "cluster")) 
        stop("Invalid Cluster")
    lexicon <- dplyr::filter_(ww, ~lang == language)
    word_l <- strsplit(tolower(char_v), "[^A-Za-z']+")
    if (is.null(cl)) {
        nrc_data <- lapply(word_l, get_nrc_values, lexicon = lexicon)
    }
    else {
        nrc_data <- parallel::parLapply(cl = cl, word_l, lexicon = lexicon, 
            get_nrc_values)
    }
    result_df <- as.data.frame(do.call(rbind, nrc_data), stringsAsFactors = F)
    my_col_order <- c("anger", "anticipation", "disgust", 
        "fear", "joy", "sadness", "surprise", 
        "trust", "negative", "positive")
    result_df[, my_col_order]
}

pre_ejemplo<-function (word_vector, language = "english", lexicon = T) 
{
    if (is.null(lexicon)) {
        lexicon <- dplyr::filter_(nrc, ~lang == language)
    }
    data <- dplyr::filter_(lexicon, ~word %in% word_vector)
    data <- dplyr::group_by_(data, ~sentiment)
    data <- dplyr::summarise_at(data, "value", sum)
    all_sent <- unique(lexicon$sentiment)
    sent_present <- unique(data$sentiment)
    sent_absent <- setdiff(all_sent, sent_present)
    if (length(sent_absent) > 0) {
        missing_data <- dplyr::data_frame(sentiment = sent_absent, 
            value = 0)
        data <- rbind(data, missing_data)
    }
    tidyr::spread_(data, "sentiment", "value")
}

#ejecutanto la nueva funcion
ejemplo(frase,language = "spanish")

```

