---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Armar la matriz de datos (Seudo matriz de contingencias)

```{r,message=TRUE}
library(dplyr)
load("D:\\Users\\usuario\\Documents\\GitHub\\EST-384\\data\\endsa.RData")
endsa<-endsa %>% filter(year==2008)
attributes(endsa)$var.labels
# 6, 7, 14
vv<-names(endsa)[c(3,10,23)]
endsa<-endsa %>% select(vv)
#VERIFICANDO QUE todos los individuos llenaron los datos
endsa<-endsa[complete.cases(endsa),]
#head(endsa[,vv])
library(fastDummies)
#dummy_cols(endsa, "sexo") #ejemplo
N<-dummy_cols(endsa,vv)
N<-N[,-c(1:3)]
N
#verificando que nos existan columnas con todos los valores en 0
apply(N, 2, sum)
# N<-N[,-7] # uso si hay alguna columnsa con datos igual a 0
## opcional
n<-sum(N)
P<-N/n
P<-as.matrix(P)
rr<-margin.table(P,1)
cc<-margin.table(P,2)
S<-diag(rr^(-0.5)) %*% (P-rr %*%t (cc))%*%diag(cc^(-0.5))
#paso2
u<-svd(S)$u
v<-svd(S)$v
Da<-diag(svd(S)$d)
#paso 3
#Coordenadas principales de filas: $F=D_r^{-1/2} U D_{\alpha}$
FF<-diag(rr^(-0.5))%*% u %*%Da
#paso 4
#Coordenadas principales de columnas: $G=D_c^{-1/2} V D_{\alpha}$
GG<-diag(cc^(-0.5))%*% v %*%Da
########################################
cumsum(svd(S)$d)/sum(svd(S)$d)
#grafico 1
names(N)
ll<-c("area_Rural",          "area_Urbana",             "ae04_No puede leer",     
 "ae04_Lee con dificultad" ,"ae04_Lee sin dificultad", "ae04_Incidencias",       
 "nup01_Nunca se caso"    , "nup01_Casado"  ,          "nup01_Convivencia"  ,    
"nup01_Viudo"            , "nup01_Divorciado"     ,   "nup01_No viven juntos")
plot(GG[,1],GG[,2],type="n")
text(GG[,1],GG[,2],labels = ll,cex=0.7)
points(FF[,1],FF[,2],col="grey")
library(FactoMineR)
#DDD
```

##Ejercicios

1. Elegir otras 3 variables y realizar el mca
2. Usar la libreria library(FactoMineR) para las tres variables previas. (Comentar los resultados)
3. Usar la library(expor)

